version: '3'

vars:
  MCBAISE_CRATE: bevy_mcbaise_fantasmagoria
  MCBAISE_WASM_TARGET: wasm32-unknown-unknown
  MCBAISE_WWW_DIR: crates/bevy_Mcbaise_Pale_Regard_Absurdia_Fantasmagoria/www
  MCBAISE_WASM_PROFILE: wasm-release
  MCBAISE_PORT: '5173'


tasks:
  demo:native:
    desc: Run the bevy_burn_human demo natively
    cmds:
      - cargo run -p bevy_burn_human

  install-python-modules:
    desc: Install required Python modules
    cmds:
      - python -m pip install --upgrade pip setuptools wheel
      - pip install packaging
      - pip install numpy
      - pip install torch
      - pip install roma
      - pip install safetensors
      - pip install anny
      - pip install pyyaml
      - pip install pillow

  export-reference:
    desc: Run the export_reference.py script
    deps:
      - task: install-python-modules
    cmds:
      - python tool/scripts/export_reference.py --output assets/model/fullbody_default.safetensors --seed 1234

  mcbaise:native:
    desc: Run the tube ride demo natively
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_native

  mcbaise:assets:preflight:
    desc: Test native asset auto-download (downloads/extracts if needed, prints paths, exits)
    env:
      MCBAISE_ASSETS_PREFLIGHT: "1"
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_native
  mcbaise:assets:self-test:
    desc: Cross-platform Rust self-test for asset download (forces download, verifies files, restores local assets)
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_native -- --assets-self-test

  mcbaise:native:youtube:
    desc: Alias for mcbaise:native:youtube:fresh
    cmds:
      - task: mcbaise:native:youtube:fresh

  mcbaise:native:youtube:fresh:
    desc: Run native tube ride + sync playback from YouTube via WebDriver (fresh Chrome profile)
    env:
      MCBAISE_NATIVE_YOUTUBE: "1"
      MCBAISE_LAUNCH_WEBDRIVER: "1"
      MCBAISE_CHROME_COOKIES_TXT: '{{default "" .CHROME_COOKIES_TXT}}'
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_youtube --features native-youtube

  mcbaise:native:youtube:default-profile:
    desc: Run native tube ride + YouTube sync using your default Chrome profile (logged-in cookies)
    env:
      MCBAISE_NATIVE_YOUTUBE: "1"
      MCBAISE_LAUNCH_WEBDRIVER: "1"
      MCBAISE_CHROME_USER_DATA_DIR: '{{.LOCALAPPDATA}}\Google\Chrome\User Data'
      MCBAISE_CHROME_PROFILE_DIR: Default
      MCBAISE_CHROME_COOKIES_TXT: '{{default "" .CHROME_COOKIES_TXT}}'
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_youtube --features native-youtube

  mcbaise:native:trace:
    desc: Run the native demo with verbose tracing and full backtrace (debug logging)
    env:
      RUST_LOG: 'debug'
      BEVY_BACKTRACE: 'full'
      WGPU_ERROR_MODE: 'nonfatal'
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_native

  mcbaise:native:mpv:
    desc: Run native tube ride + sync playback from mpv (YouTube via yt-dlp)
    env:
      MCBAISE_NATIVE_MPV: "1"
      MCBAISE_MPV_URL: '{{default "" .MPV_URL}}'
      MCBAISE_MPV_PATH: '{{default "" .MPV_PATH}}'
      MCBAISE_MPV_EXTRA_ARGS: '{{default "" .MPV_EXTRA_ARGS}}'
      MCBAISE_MPV_COOKIES_FILE: '{{default "" .MPV_COOKIES_FILE}}'
      MCBAISE_MPV_COOKIES_FROM_BROWSER: '{{default "" .MPV_COOKIES_FROM_BROWSER}}'
      MCBAISE_MPV_YTDL_RAW_OPTIONS: '{{default "" .MPV_YTDL_RAW_OPTIONS}}'
    cmds:
      - cargo run --bin bevy_mcbaise_fantasmagoria_mpv --features native-mpv

  mcbaise:wasm:toolchain:
    desc: Ensure Rust wasm target is installed
    cmds:
      - rustup target add {{.MCBAISE_WASM_TARGET}}

  mcbaise:wasm:bindgen:install:
    desc: Install wasm-bindgen-cli (dispatches to platform-specific installer)
    cmds:
      - |-
        set -euo pipefail
        OS=$(uname -s 2>/dev/null || echo "Windows")
        case "$OS" in
          Darwin*|Linux*|*BSD*)
            task mcbaise:wasm:bindgen:install:posix
            ;;
          *)
            task mcbaise:wasm:bindgen:install:windows
            ;;
        esac

  mcbaise:wasm:bindgen:install:posix:
    desc: Install wasm-bindgen-cli on POSIX (Linux/macOS)
    status:
      - wasm-bindgen --version
    cmds:
      - |-
        set -euo pipefail
        # Try to read the wasm-bindgen version from Cargo.lock to match schema
        # Simpler approach: parse Cargo.lock for the wasm-bindgen package version
        WB_VER=$(awk '/^\[\[package\]\]/{p=0} /name = "wasm-bindgen"/{p=1} p && /version =/ {gsub(/"/,"",$3); print $3; exit}' Cargo.lock || true)
        if [ -n "$WB_VER" ]; then
          echo "Installing wasm-bindgen-cli v${WB_VER} to match Cargo.lock"
          cargo install -f wasm-bindgen-cli --version "$WB_VER" || cargo install wasm-bindgen-cli --locked
        else
          echo "Could not detect wasm-bindgen version from Cargo.lock; installing latest wasm-bindgen-cli"
          cargo install -f wasm-bindgen-cli --locked
        fi

  mcbaise:wasm:bindgen:install:windows:
    desc: Install wasm-bindgen-cli on Windows (PowerShell)
    status:
      - wasm-bindgen --version
    cmds:
      - |-
        @echo off
        REM Use PowerShell to parse Cargo.lock for wasm-bindgen version if present, then call cargo install
        powershell -NoProfile -Command "
          $wbv='';
          if (Test-Path 'Cargo.lock') {
            $content = Get-Content -Raw 'Cargo.lock' -ErrorAction SilentlyContinue;
            if ($content -match 'name = "wasm-bindgen"[\s\S]*?version = "([0-9\.]+)"') { $wbv = $Matches[1] }
          }
          if ($wbv) { Write-Host \"Installing wasm-bindgen-cli v$wbv to match Cargo.lock\"; exit 0 } else { Write-Host \"No version detected in Cargo.lock\"; exit 2 }
        " || (
          REM If powershell command returned 0 we still need to install; try to retrieve version again and install
          powershell -NoProfile -Command "if (Test-Path 'Cargo.lock') { $c = Get-Content -Raw 'Cargo.lock'; if ($c -match 'name = \"wasm-bindgen\"[\s\S]*?version = \"([0-9\.]+)\"') { $v=$Matches[1]; Write-Host \"Installing wasm-bindgen-cli v$v\"; exit 0 } else { exit 2 } } else { exit 2 }" || true
        )
        REM Best-effort install: install matching version if we found it, otherwise install locked/latest
        powershell -NoProfile -Command "
          $wbv='';
          if (Test-Path 'Cargo.lock') { $content = Get-Content -Raw 'Cargo.lock' -ErrorAction SilentlyContinue; if ($content -match 'name = \"wasm-bindgen\"[\s\S]*?version = \"([0-9\.]+)\"') { $wbv=$Matches[1] } }
          if ($wbv) { npm run -s || exit 0 }
        " || true
        REM Fallback: run cargo install (simple, works on Windows with cargo present)
        cargo install -f wasm-bindgen-cli --locked || cargo install wasm-bindgen-cli

  mcbaise:wasm:build:
    desc: Build the tube ride demo for wasm and generate wasm-bindgen package into www/pkg
    deps:
      - task: mcbaise:wasm:toolchain
      - task: mcbaise:wasm:bindgen:install
      - task: mcbaise:wasm:ensure-assets
    cmds:
      - |-
        set -euo pipefail
        # Ensure the embedded model asset exists; if not, generate it
        ASSET_PATH="assets/model/fullbody_default.safetensors"
        if [[ ! -f "$ASSET_PATH" ]]; then
          echo "Asset $ASSET_PATH missing — running task export-reference to generate it"
          task export-reference
        fi
        cargo build -p {{.MCBAISE_CRATE}} --profile {{.MCBAISE_WASM_PROFILE}} --target {{.MCBAISE_WASM_TARGET}}
      - wasm-bindgen --target web --no-typescript --out-dir {{.MCBAISE_WWW_DIR}}/pkg --out-name {{.MCBAISE_CRATE}} target/{{.MCBAISE_WASM_TARGET}}/{{.MCBAISE_WASM_PROFILE}}/{{.MCBAISE_CRATE}}.wasm

  mcbaise:wasm:serve:
    desc: Serve the repo root so /assets is available, then open the web demo URL manually
    deps:
      - task: naga:validate
      - task: mcbaise:wasm:build
    cmds:
      - |
        echo Serve started. Open:
        echo http://localhost:{{.MCBAISE_PORT}}/{{.MCBAISE_WWW_DIR}}/
        python -m http.server {{.MCBAISE_PORT}} || py -m http.server {{.MCBAISE_PORT}}

  mcbaise:wasm:ensure-assets:
    desc: "Ensure embedded model assets exist (cross-platform). Runs `export-reference` if missing."
    cmds:
      - |-
        set -euo pipefail
        ASSET="assets/model/fullbody_default.safetensors"
        if [ -f "$ASSET" ]; then
          echo "Found $ASSET"
          exit 0
        fi
        echo "$ASSET missing; running export-reference to create it"
        # On Windows, `task` should still be available; run the export task which depends on install-python-modules
        task export-reference

  
  update-chromedriver:mac:brew:
    desc: macOS - upgrade chromedriver via Homebrew if available
    status:
      - brew --version
    cmds:
      - |-
        set -euo pipefail
        # Try to upgrade; if installed, reinstall as a fallback; otherwise install
        if brew list --cask chromedriver >/dev/null 2>&1; then
          brew upgrade chromedriver || brew reinstall --cask chromedriver || true
        else
          brew install --cask chromedriver || true
        fi

        # Verify Chrome and chromedriver major versions; fall back to download if they mismatch
        CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        CHROME_MAJOR=""
        if [[ -x "$CHROME_BIN" ]]; then
          CHROME_MAJOR=$($CHROME_BIN --version 2>/dev/null | awk '{print $3}' | cut -d. -f1 || true)
        fi
        CD_MAJOR=$(chromedriver --version 2>/dev/null | awk '{print $2}' | cut -d. -f1 || true)
        if [[ -n "$CHROME_MAJOR" && -n "$CD_MAJOR" && "$CHROME_MAJOR" != "$CD_MAJOR" ]]; then
          echo "chromedriver major ($CD_MAJOR) does not match Chrome major ($CHROME_MAJOR); falling back to direct download"
          task update-chromedriver:mac:download
        else
          echo "chromedriver appears to match Chrome (major: ${CHROME_MAJOR:-unknown})"
        fi

  update-chromedriver:mac:download:
    desc: macOS - download matching chromedriver and install to {{default "/opt/homebrew/bin" .UPDATE_CHROMEDRIVER_INSTALL_DIR}}
    cmds:
      - |
        set -euo pipefail
        CHROME_BIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        if [[ ! -x "$CHROME_BIN" ]]; then
          echo "Chrome binary not executable at $CHROME_BIN; try passing --chrome-bin env var"; exit 1
        fi
        CHROME_VERSION_RAW="$($CHROME_BIN --version 2>/dev/null || true)"
        CHROME_VERSION=$(echo "$CHROME_VERSION_RAW" | awk '{print $3}')
        CHROME_MAJOR=$(echo "$CHROME_VERSION" | cut -d. -f1)
        echo "Detected Chrome version: $CHROME_VERSION"
        LATEST_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR}"
        DRIVER_VERSION=$(curl -fsSL "$LATEST_URL" || true)
        if [[ -z "$DRIVER_VERSION" ]]; then
          echo "No matching chromedriver LATEST_RELEASE for $CHROME_MAJOR; falling back to latest"; DRIVER_VERSION=$(curl -fsSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        fi
        ARCH=$(uname -m)
        if [[ "$ARCH" == "arm64" || "$ARCH" == "aarch64" ]]; then
          ZIP_NAME="chromedriver_mac_arm64.zip"
        else
          ZIP_NAME="chromedriver_mac64.zip"
        fi
        DOWNLOAD_URL="https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/${ZIP_NAME}"
        TMP_ZIP="/tmp/chromedriver-${DRIVER_VERSION}.zip"
        TMP_DIR="/tmp/chromedriver-${DRIVER_VERSION}"
        echo "Download URL: $DOWNLOAD_URL"
        curl -fL -o "$TMP_ZIP" "$DOWNLOAD_URL"
        unzip -q -d "$TMP_DIR" "$TMP_ZIP"
        chmod +x "$TMP_DIR/chromedriver"
        sudo mkdir -p "{{default "/opt/homebrew/bin" .UPDATE_CHROMEDRIVER_INSTALL_DIR}}" || true
        sudo mv "$TMP_DIR/chromedriver" "{{default "/opt/homebrew/bin" .UPDATE_CHROMEDRIVER_INSTALL_DIR}}/chromedriver"
        sudo chmod +x "{{default "/opt/homebrew/bin" .UPDATE_CHROMEDRIVER_INSTALL_DIR}}/chromedriver"
        echo "Installed chromedriver to {{default "/opt/homebrew/bin" .UPDATE_CHROMEDRIVER_INSTALL_DIR}}/chromedriver"

  update-chromedriver:linux:download:
    desc: Linux - download matching chromedriver and install to /usr/local/bin (requires sudo)
    cmds:
      - |
        set -euo pipefail
        CHROME_BIN=$(command -v google-chrome-stable || command -v google-chrome || command -v chromium-browser || true)
        if [[ -z "$CHROME_BIN" ]]; then
          echo "Cannot find chrome/chromium binary on PATH"; exit 1
        fi
        CHROME_VERSION_RAW="$($CHROME_BIN --version 2>/dev/null || true)"
        CHROME_VERSION=$(echo "$CHROME_VERSION_RAW" | grep -Eo '[0-9]+(\.[0-9]+)+' | head -n1)
        CHROME_MAJOR=$(echo "$CHROME_VERSION" | cut -d. -f1)
        echo "Detected Chrome version: $CHROME_VERSION"
        DRIVER_VERSION=$(curl -fsSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR}" || true)
        if [[ -z "$DRIVER_VERSION" ]]; then
          DRIVER_VERSION=$(curl -fsSL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        fi
        ZIP_NAME="chromedriver_linux64.zip"
        DOWNLOAD_URL="https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/${ZIP_NAME}"
        TMP_ZIP="/tmp/chromedriver-${DRIVER_VERSION}.zip"
        TMP_DIR="/tmp/chromedriver-${DRIVER_VERSION}"
        echo "Download URL: $DOWNLOAD_URL"
        curl -fL -o "$TMP_ZIP" "$DOWNLOAD_URL"
        unzip -q -d "$TMP_DIR" "$TMP_ZIP"
        chmod +x "$TMP_DIR/chromedriver"
        sudo mv "$TMP_DIR/chromedriver" /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        echo "Installed chromedriver to /usr/local/bin/chromedriver"

  update-chromedriver:windows:choco:
    desc: Windows - install chromedriver via Chocolatey (requires choco)
    status:
      - choco --version
    cmds:
      - choco upgrade chromedriver -y || choco install chromedriver -y

  update-chromedriver:
    desc: Cross-platform helper that picks the right platform-specific task
    cmds:
      - |
        set -euo pipefail
        OS=$(uname -s 2>/dev/null || echo "Windows")
        case "$OS" in
          Darwin*)
            if command -v brew >/dev/null 2>&1; then
              echo "Using Homebrew to update chromedriver"
              task update-chromedriver:mac:brew
            else
              echo "Homebrew not found; downloading chromedriver directly"
              task update-chromedriver:mac:download
            fi
            ;;
          Linux*)
            echo "Downloading chromedriver for Linux"
            task update-chromedriver:linux:download
            ;;
          *)
            # Assume Windows
            echo "Using Chocolatey on Windows"
            task update-chromedriver:windows:choco
            ;;
        esac
  naga:detect:
    desc: Detect if `naga` (naga-cli) is available on PATH
    cmds:
      - |
        if command -v naga >/dev/null 2>&1; then
          echo "naga found: $(naga --version 2>/dev/null || echo unknown)"
          exit 0
        fi
        if [ -f "${HOME}/.cargo/bin/naga" ] || [ -f "${USERPROFILE}\\.cargo\\bin\\naga.exe" ]; then
          echo "naga found in cargo bin"
          exit 0
        fi
        echo "naga not found"
        exit 1

  naga:install:posix:
    desc: Install `naga-cli` via `cargo` on POSIX systems
    cmds:
      - |
        set -euo pipefail
        echo "Installing naga-cli via cargo..."
        cargo install naga-cli || cargo install --locked naga-cli || true

  naga:install:windows:
    desc: Install `naga-cli` on Windows (PowerShell)
    cmds:
      - 'echo Installing naga-cli via cargo on Windows'
      - 'cargo install naga-cli || cargo install --locked naga-cli || echo cargo install failed'

  naga:install:
    desc: Cross-platform installer for naga-cli
    cmds:
      - |-
        set -euo pipefail
        OS=$(uname -s 2>/dev/null || echo "Windows")
        case "$OS" in
          Darwin*|Linux*|*BSD*) task naga:install:posix ;;
          *) task naga:install:windows ;;
        esac

  naga:validate:
    desc: Validate a WGSL shader file with naga-cli (usage task naga:validate -- file=path)
    vars:
      file: 'crates/bevy_Mcbaise_Pale_Regard_Absurdia_Fantasmagoria/src/mcbaise_tube.wgsl'
    cmds:
      - |-
        if [ -z "{{.file}}" ]; then
          echo "No file specified. Usage: task naga:validate -- file=path/to/shader.wgsl"; exit 2
        fi
        if ! command -v naga >/dev/null 2>&1; then
          echo "naga not found; attempting install"; task naga:install
        fi
        echo "Preprocessing {{.file}} for validator (stripping host directives)..."
        if command -v mktemp >/dev/null 2>&1 && command -v sed >/dev/null 2>&1; then
          TMPFILE=$(mktemp 2>/dev/null || echo "${TMPDIR:-/tmp}/mcbaise_naga_pre.wgsl")
          sed '/^[[:space:]]*#import/d; s/#{[^}]*}/0/g' "{{.file}}" > "$TMPFILE"
          echo "Validating preprocessed shader: $TMPFILE"
          naga "$TMPFILE" --input-kind wgsl || true
          rm -f "$TMPFILE"
        else
          python tool/scripts/validate_wgsl.py "{{.file}}"
        fi

  # Run with specific WGPU backend (env-driven). Example: `task mcbaise:run:backend -- backend=vulkan`
  mcbaise:run:backend:
    desc: Run native demo with a specified WGPU backend (set `backend` var)
    vars:
      backend: 'vulkan'
    env:
      WGPU_BACKEND: '{{.backend}}'
      RUST_BACKTRACE: 'full'
      WGPU_ERROR_MODE: 'nonfatal'
      RUST_LOG: 'bevy_render=error,wgpu=error,wgpu_core=error'
    cmds:
      - cd crates/bevy_Mcbaise_Pale_Regard_Absurdia_Fantasmagoria && cargo run --bin bevy_mcbaise_fantasmagoria_native

  mcbaise:run:backend:vulkan:
    desc: Run demo with Vulkan backend
    cmds:
      - task: mcbaise:run:backend -- backend=vulkan

  mcbaise:run:backend:dx12:
    desc: Run demo with DirectX 12 backend
    cmds:
      - task: mcbaise:run:backend -- backend=dx12

  mcbaise:run:backend:dx11:
    desc: Run demo with DirectX 11 backend
    cmds:
      - task: mcbaise:run:backend -- backend=dx11

  mcbaise:run:backend:metal:
    desc: Run demo with Metal backend (macOS)
    cmds:
      - task: mcbaise:run:backend -- backend=metal

  mcbaise:run:backend:opengl:
    desc: Run demo with OpenGL backend
    cmds:
      - task: mcbaise:run:backend -- backend=gl

  # Tests
  mcbaise:test:unit:
    desc: Run unit tests for the main crate
    cmds:
      - cargo test -p bevy_mcbaise_fantasmagoria

  mcbaise:test:workspace:
    desc: Run all workspace tests
    cmds:
      - cargo test --workspace