//! Packed binary structs for the runtime artifact.
//!
//! TODO: flesh out once the Python export format is finalized.

#[derive(Debug, Clone, Default)]
pub struct PackedModelInfo {
    pub version: u32,
}

impl PackedModelInfo {
    pub fn new(version: u32) -> Self {
        Self { version }
    }
}

/// Placeholder for the eventual packed artifact format.
///
/// Today we rely on safetensors reference files generated by the Python
/// implementation. Once the import tool produces compact binaries, this
/// struct can carry versioning and header information.
#[derive(Debug, Clone, Default)]
pub struct PackedArtifactHeader {
    pub version: u32,
}
